### ISSUE TITLE
Specifications: 3-button remote (Remora)

### ISSUE THREAD

**Issue by CexyNature** [pimbongaerts/altimeter#1]
Pim awesome project!
I was wondering if the 3-button remote you mention in README is a custom made product? and if these are push buttons?

> On the right side, there is an Ikelite connector to connect with the camera (power and trigger), another Ikelite connector for the 3-button remote (Remora), ...

Thanks, I look forward to the next iteration.

**Comment by pimbongaerts** [comment]
Thanks Cesar! It was a product that Backscatter used to carry (maybe produce?) - but not anymore unfortunately, and cannot really find it anywhere on the web. It has 3 push buttons and an Ikelite connector.

**Comment by CexyNature** [comment]
Thanks! It is super great idea to have a keypad with buttons. I have been looking other options like the [Blue Robotics switch](https://bluerobotics.com/store/comm-control-power/switch/switch-10-5a-r1/) or other underwater rated buttons (but these cannot be mounted in M10 holes). 

Having a keypad with three button and just one cable penetrator is an amazing setup!

Many thanks! 😃
